=== GermanWithSherman/Berlin/Data/_schema/NPC.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type":"object",
    "required": [
    ],
    "additionalProperties": false,
    
    "properties": {
        "$schema" :{"type":"string"},
        "TemplateID": {"type":"string" },
        "GenderVisible": {"type":"string" },
        "NameNick": {"type":"string" },
        "NameFirst": {"type":"string" },
        "NameLast": {"type":"string" },
        "Schedules": {
            "patternProperties": {
                "^.*$": {
                    "$ref": "./TimeFilters.json"
                }
            }  
        },
        "TexturePath" : { "$ref": "./ConditionalString.json" }
    }
    
}

=== GermanWithSherman/Berlin/Data/npcs/school_kathy.json
{
    "TemplateID": "default_female",
    "NameFirst": "Katharina",
    "NameNick": "Kathy",
    "NameLast": "Gerhard",
    "TexturePath": {
        "Values":{
            "5_d":{
                "Value": "npc/school/students/kathyPortrait.jpg",
                "Condition": "b_school_kathy_enslaved=false"
            },
            "5_enslaved":{
                "Value": "npc/school/students/kathyPortraitE.jpg",
                "Condition": "b_school_kathy_enslaved=true"
            }
        }
    },
    "Schedules":{
        "dahlem/school/dorm.3_314": {
            "5_goesToSchool": {
                "TimeStart": 0,
                "TimeEnd": 2359,
                "Condition":"b_school_kathy_enslaved=false"
            },
            "5_enslaved": {
                "TimeStart": 0,
                "TimeEnd": 2359,
                "Condition":"b_school_kathy_enslaved_known=true"
            }
        }
    }
}

=== GermanWithSherman/Berlin/Data/npcs/school_janine.json
{
    "TemplateID": "default_female",
    "NameFirst": "Janine",
    "NameLast": "Schneider",
    "TexturePath": {
        "Value": "npc/school/students/janinePortrait.jpg"
    },
    "Schedules":{
        "dahlem/school/dorm.2_211": {
            "0": {
                "TimeStart": 0,
                "TimeEnd": 2359
            }
        }
    }
}

=== GermanWithSherman/Berlin/Data/npcs/school_michel.json
{
    "TemplateID": "default_male",
    "NameFirst": "Michel",
    "NameLast": "Frank",
    "TexturePath": {
        "Value": "npc/school/students/michelPortrait.png"
    },
    "Schedules":{
        "dahlem/school/dorm.1_107": {
            "0": {
                "TimeStart": 0,
                "TimeEnd": 2359
            }
        }
    }
}

=== GermanWithSherman/Berlin/Data/mods/school_kathy/npcs/school_kathy.json
{
    "TemplateID": "default_female",
    "NameFirst": "Katharina",
    "NameNick": "Kathy",
    "NameLast": "Gerhard",
    "TexturePath": {
        "Values":{
            "5_default":{
                "Condition": "b_school_kathy_enslaved=false"
            },
            "5_enslaved":{
                "Value": "npc/school/students/kathyPortraitE.jpg",
                "Condition": "b_school_kathy_enslaved=true"
            }
        }
    },
    "Schedules":{
        "dahlem/school/dorm.3_314": {
            "5_default": {
                "Condition":"b_school_kathy_enslaved=false"
            },
            "5_enslaved": {
                "TimeStart": 0,
                "TimeEnd": 2359,
                "Condition":"b_school_kathy_enslaved_known=true"
            }
        }
    }
}

=== GermanWithSherman/Berlin/Data/npcs/school_gabriel.json
{
    "TemplateID": "default_male",
    "NameFirst": "Gabriel",
    "NameLast": "Jung",
    "TexturePath": {
        "Value": "npc/school/students/gabrielPortrait.png"
    },
    "Schedules":{
        "dahlem/school/dorm.1_108": {
            "0": {
                "TimeStart": 0,
                "TimeEnd": 2359
            }
        }
    }
}

=== GermanWithSherman/Berlin/Data/npcs/school_pierre.json
{
    "TemplateID": "default_male",
    "NameFirst": "Pierre",
    "NameLast": "Schwarz",
    "TexturePath": {
        "Value": "npc/school/students/pierrePortrait.png"
    },
    "Schedules":{
        "dahlem/school/dorm.3_314": {
            "0": {
                "TimeStart": 1000,
                "TimeEnd": 2359
            }
        }
    }
}
