=== GermanWithSherman/Berlin/Data/_schema/NPCTemplate.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "NPCTemplate",
    "description": "NPCTemplate schema.",
    "default": {},
    "examples": [
        
    ],
    "required": [
    ],
    "additionalProperties": false,
    
    "properties": {
        "$schema" :{"type":"string"},
        "Parent": {"type":"string" },
        "Age": { "$ref": "./ValueInt.json" },
        "BMI": { "$ref": "./ValueFloat.json" },
        "BreastVolume": { "$ref": "./ValueInt.json" },
        "HairLength": { "$ref": "./ValueInt.json" },
        "Height": { "$ref": "./ValueInt.json" },
        "PenisLength": { "$ref": "./ValueInt.json" },
        "GenderVisible": { "$ref": "./ValueString.json" },
        "NameFirst": { "$ref": "./ValueString.json" },
        "NameLast": { "$ref": "./ValueString.json" },
        "Schedules": {
            "patternProperties": {
                "^.*$": {
                    "$ref": "./TimeFilters.json"
                }
            }  
        }
    }
}

=== GermanWithSherman/Berlin/Data/npctemplates/default_female.json
{
    "Parent":"default",
    "NameFirst":{"ValueType":"WeightedStringList","Key":"names_first_female_90s"},
    "GenderVisible":{"ValueType":"Plain","Value":"f"},
    "BreastVolume":{"ValueType":"RandomRange","Parameters":{"Min":"300","Max":"1200"}},
    "HairLength":{"ValueType":"Plain","Value":3000000},
    "Height":{"ValueType":"Plain","Value":1700},
    "PenisLength":{"ValueType":"Plain","Value":0},
    "BMI": {}
}
